### ISSUE TITLE
Homepage > Latest News doesn't preserve image & text at narrow width

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#68]
Normal:

> <img width="625" alt="screen shot 2015-12-22 at 12 09 35 pm" src="https://cloud.githubusercontent.com/assets/59118/11961207/12c1d0c6-a8a5-11e5-9a59-39effafe68b2.png">

At narrow width:

> <img width="607" alt="screen shot 2015-12-22 at 12 09 43 pm" src="https://cloud.githubusercontent.com/assets/59118/11961209/1586adb8-a8a5-11e5-916a-a1459ab78885.png">

At narrow width, the book image is much too large and pushes the text down below the image. I would like the image to shrink so the text can stay on the same line as the image.

**Comment by JoernT** [comment]
that can probably solved quite easily by applying an img-responsive class. I'll have a look...

**Comment by dizzzz** [comment]
If the page is http://localhost:8080/exist/apps/hsg-shell/ it looks like it is solved?
the class is available, the image is actually expanded on smaller screen width, and is located side-by-side for wider screens.

Close?

**Comment by joewiz** [comment]
@dizzzz Thanks for taking a look. The issue isn't solved yet. At smaller screen width the image is too large. This is especially evident at iPad screen sizes, where the image takes up the entire width of the screen. At phone screen sizes in portrait orientation, full width is probably acceptable, but in landscape the image is too large. I think @JoernT had some ideas for improving this.

As to the overhanging line in the tweets, thanks for mentioning this. To ensure a space appears between links (whitespace between consecutive elements is collapsed to zero in eXist serialization), I had to hard code an additional space, but I think I need to switch it from non-breaking space to a regular space at https://github.com/eXistSolutions/hsg-shell/blob/master/modules/app.xqm#L271.

**Comment by line-o** [comment]
<img width="620" alt="screen shot 2016-02-19 at 18 39 44" src="https://cloud.githubusercontent.com/assets/657222/13183651/47c4ded2-d738-11e5-906d-70c7165baebf.png">
